import { WEAPONS } from '../game/config';

const section = (id, title, text, extra = {}) => ({ id, title, text, ...extra });
export const GUIDE_UPDATED = 'October 1, 2026';
export const LUCK_ODDS = [
  ['T1', 'Fabric / Plate / Binding / Mechanism', '17% each', '4%', '72%'],
  ['T2', 'Fabric / Plate / Binding / Mechanism', '5.5% each', '1%', '23%'],
  ['T3', 'Fabric / Plate / Binding / Mechanism', '1.1% each', '0.6%', '5%'],
];
export const CHAPTERS = [
  { id: 'getting-started', title: 'First Five Minutes', icon: 'compass', summary: 'Your first steps in Westfall. Connect, prepare, and leave safety with a plan.', tags: 'start beginner onboarding', sections: [
    section('welcome-to-westfall', 'Welcome to Westfall', 'LastZHood is a browser-based, multiplayer survival game set in Westfall. Fight infected enemies, collect parts, build equipment and work with other survivors. The game is in Early Access: systems and balance may change.', { note: 'This field guide is public. You only need a connected, signed-in wallet when entering the game or using account features.' }),
    section('first-deployment', 'Prepare your first deployment', 'Start with a short checklist. You do not need to buy a package to learn the game.', { steps: ['Choose START GAME to open character preparation.', 'Connect your EVM wallet on Robinhood Chain (chain ID 4663), then sign in with the wallet identity message.', 'On your first visit, choose a call sign of 2–18 characters. Select your character appearance.', 'Join when the character screen is ready. You start with a Glock 18.', 'Practise movement and aiming in the central safe area. Firing is disabled there; check your surroundings before leaving.'] }),
    section('first-supply-run', 'Your first supply run', 'Keep your first trip short. Approach a small group, leave space to retreat and reload before the next fight.', { cards: [['01 / MOVE', 'Use WASD or the arrow keys. Save stamina for a retreat.'], ['02 / COLLECT', 'Check your inventory after picking up supplies and crafting parts.'], ['03 / BUILD', 'Open the Workshop with C. Compare available materials against the recipe requirements.']], related: ['controls', 'survival', 'crafting'] }),
  ] },
  { id: 'controls', title: 'Controls & HUD', icon: 'keyboard', summary: 'Movement, quick access and the information that keeps you alive.', tags: 'keys hotkeys mobile map zoom', sections: [
    section('keyboard-controls', 'Keyboard controls', 'Gameplay shortcuts apply while you are alive and are not typing or using a blocking panel.', { table: { headers: ['Input', 'Action'], rows: [['WASD / Arrow keys', 'Move'], ['Mouse / Left mouse button', 'Aim / Fire'], ['Shift / R', 'Sprint / Reload'], ['I', 'Toggle the quick menu'], ['C / P', 'Workshop / Statistics'], ['G / M', 'Alliance / Market'], ['Q / F', 'Medkit / First Aid Kit'], ['1–0', 'Equip an assigned, owned weapon'], ['Tab', 'Leaderboard'], ['Escape', 'Close an open panel; otherwise open Settings'], ['Mouse wheel', 'Camera zoom']] } }),
    section('quick-menu', 'The quick menu', 'Press I to open or close the quick menu. Select Inventory at the top, Workshop at the bottom, Zone Map on the left or Statistics on the right. M opens the Market, not the map.'),
    section('read-your-hud', 'Read your HUD', 'Watch your HP, stamina, equipped weapon, magazine and reserve ammunition. Action progress shows when healing or reloading is underway. Damage numbers report hits; the target health bar helps you judge the remaining threat.', { cards: [['HP', 'Heal before committing to another fight.'], ['STAMINA', 'Sprint deliberately and allow regeneration.'], ['AMMO', 'Check both your magazine and reserve ammunition.']] }),
    section('mobile-and-settings', 'Mobile & settings', 'On touch devices, use the on-screen movement and fire controls and the HUD buttons to open panels. Settings lets you adjust sound, graphics and camera zoom. Your preferences are saved on the current browser.', { related: ['weapons', 'survival'] }),
  ] },
  { id: 'wallet', title: 'Wallet & Account', icon: 'wallet', summary: 'Understand connection, identity and persistent progression.', tags: 'account login sign in nickname chain robinhood', sections: [
    section('connect-and-sign-in', 'Connect is not sign-in', 'Connecting lets the site see your selected wallet address. Signing the identity message establishes your game account. The identity signature is not an ETH transfer. A market payment is a separate transaction requiring its own wallet approval.', { steps: ['Select CONNECT ROBINHOOD WALLET.', 'Switch to Robinhood Chain if your wallet is on a different network.', 'Sign the identity message for the selected address.', 'Complete your call sign on your first visit, then enter the game.'] }),
    section('network-and-identity', 'Use the correct identity', 'The network is Robinhood Chain, chain ID 4663. Your selected wallet must match your signed-in account. Switching addresses may require signing in again. Your progress belongs to that account, not to a character skin.', { note: 'Never share your recovery phrase or private key. This guide does not require either.' }),
    section('saved-progress', 'Saved progress', 'Account progression is saved by the game. A page refresh reconnects through the account flow; it does not make a soldier recovery or mission timer finish early. Browser preferences such as sound and graphics are stored locally.', { related: ['getting-started', 'soldiers', 'faq'] }),
  ] },
  { id: 'survival', title: 'Combat & Safe Zones', icon: 'shield', summary: 'Manage space, stamina and recovery before the next encounter.', tags: 'hp heal medkit first aid energy drink death respawn safety', sections: [
    section('combat-basics', 'Fight with room to retreat', 'Aim toward the threat, fire outside safe areas and reload with R. Weapon range matters: a close-range weapon will not replace a long-range rifle. Watch attack wind-ups and break line of sight when you need breathing room.'),
    section('safe-zones', 'Safe areas & shelters', 'The central outpost has a 14 m safe radius. Enterable building interiors also act as shelters: infected enemies cannot enter or damage you there, and environmental threat effects are blocked. You cannot fire from a safe area.', { note: 'Do not confuse shelter protection from NPCs with alliance friendly-fire rules. Check the game’s current PvP and team settings.' }),
    section('healing-supplies', 'Healing supplies', 'Use the inventory or the healing shortcuts when an item is available. Healing takes time; watch the progress indicator rather than assuming it is instant. The Heal statistic can improve the base healing amount.', { table: { headers: ['Supply', 'Base effect', 'Use time', 'Carry limit'], rows: [['Medkit / Q', '+50 HP', '3 seconds', '3'], ['First Aid Kit / F', '+25 HP', '1.5 seconds', '5'], ['Energy Drink / Inventory', '2× stamina regeneration', '60-second effect', '10']] } }),
    section('energy-and-respawn', 'Energy & recovery', 'An Energy Drink doubles stamina regeneration for one minute. Using another refreshes the duration; it does not create an unlimited stacking multiplier. Infected loot can contain one, but drops are not guaranteed. If you die, use the respawn flow to return to the central area. The current Early Access rules do not apply an inventory loss on death.', { related: ['controls', 'alliance', 'soldiers'] }),
  ] },
  { id: 'weapons', title: 'Weapons & Inventory', icon: 'crosshair', summary: 'Unlock your arsenal and set up fast weapon switching.', tags: 'glock ak ammunition ammo equip locked slots', sections: [
    section('unlock-your-arsenal', 'Unlock your arsenal', 'The Glock 18 is your starting weapon. Other weapons must be unlocked through crafting. The inventory can show the full catalog with locked entries, or only weapons you own. Selecting a locked weapon does not unlock it.'),
    section('weapon-reference', 'Weapon reference', 'Use this as a base magazine and range reference. Range is shown in world units; upgrades and combat conditions can change practical effectiveness.', { table: { headers: ['Weapon', 'Role', 'Magazine', 'Base range'], rows: WEAPONS.map(w => [w.name, w.type.toLowerCase(), String(w.mag), String(w.range)]) } }),
    section('weapon-shortcuts', 'Assign your weapon slots', 'Assign a number from 1–0 on a weapon card in the inventory. Each slot is unique. The default assignments are Glock 18 on 1 and AK-47 on 2; a shortcut only equips a weapon you own. Shortcuts do not activate while a blocking panel is open.', { steps: ['Open Inventory from the quick menu.', 'Choose an owned weapon and assign a number.', 'Close the panel, then press the number to equip it.'], related: ['crafting', 'controls'] }),
  ] },
  { id: 'crafting', title: 'Workshop & Equipment', icon: 'wrench', summary: 'Turn collected parts into weapons and a complete equipment loadout.', tags: 'craft upgrade helmet vest pants boots gloves backpack material calibration', sections: [
    section('workshop-workflow', 'Read a recipe before crafting', 'Open the Workshop with C. Choose the relevant weapon, upgrade or equipment recipe and compare your available quantities against the requirements. The panel shows any Gold, material or level condition you still need to meet.', { steps: ['Select the item or upgrade you want.', 'Read its effect and required parts.', 'Collect the missing quantities; item rarity and tier matter.', 'Craft when the displayed conditions are met, then equip the result.'] }),
    section('equipment-slots', 'Six equipment slots', 'Build a balanced loadout instead of focusing on a single slot. The inventory and recipe preview show each item’s actual bonuses.', { cards: [['HELMET', 'Head protection'], ['VEST', 'Torso protection'], ['PANTS', 'Lower-body equipment'], ['GLOVES', 'Hand equipment'], ['BOOTS', 'Foot equipment'], ['BACKPACK', 'Carry equipment']] }),
    section('materials-and-upgrades', 'Materials, tiers & upgrades', 'Equipment uses Fabric, Plate, Binding and Mechanism families with T1, T2 and T3 variants. Calibration is used where the upgrade recipe calls for it. Weapon recipes use Common, Uncommon and Rare parts. A higher-tier material does not automatically satisfy a lower-tier recipe.', { note: 'Crafting, upgrading and material conversion are separate actions. Use the displayed recipe for the exact cost and result; do not assume conversions are free or reversible.' }),
    section('equipment-progression', 'Build, equip, improve', 'Equipment has three tiers and its own upgrade progression. Crafting an item and equipping it are different steps. Check the owned-item list after crafting, compare its bonuses, then place it in the appropriate slot. Weapon upgrades also have limits shown by the Workshop.', { related: ['weapons', 'market', 'faq'] }),
  ] },
  { id: 'enemies', title: 'Enemies & Bosses', icon: 'biohazard', summary: 'Recognise threats and respect the large encounters.', tags: 'zombie hive bees armored hellhound immolator boss map hansel venom', sections: [
    section('infected-threats', 'Infected threats', 'Regular infected are only the beginning. Hellhounds close distance, armored enemies require sustained pressure, Immolators bring fire and Hive enemies send bees. Keep an escape route, watch the attack animation and avoid being surrounded.', { cards: [['FAST THREATS', 'Create space before reloading.'], ['ARMORED THREATS', 'Allow time and ammunition for the fight.'], ['AREA THREATS', 'Move out of persistent hazards.']] }),
    section('boss-reference', 'Boss reference', 'Boss fights have distinct attack patterns. Learn the warning cues and move before the attack lands. These locations identify their territories, not a promise that a boss is always alive there.', { table: { headers: ['Boss', 'Territory', 'Attacks to watch'], rows: [['HANSEL', 'East Junction', 'Laser, rocket salvo, giant leap'], ['CRIMSON VENOM', 'West Junction', 'Burning web, liquid shift, slash'], ['XENOMORPH', 'South Junction', 'Long leap, claw, bite, tail strike'], ['ASH TITAN', 'North Junction', 'Earthquake, lava pools, crushing blow']] } }),
    section('boss-tracking', 'Track before committing', 'Open the Zone Map from the quick menu or HUD. Choose a boss to track and use the in-game status and distance indicators. Prepare healing and ammunition before travelling to its territory.', { related: ['survival', 'alliance', 'soldiers'] }),
  ] },
  { id: 'alliance', title: 'Alliances', icon: 'users', summary: 'Coordinate with friends and control friendly fire within your team.', tags: 'clan team group invite code friendly fire', sections: [
    section('create-or-join', 'Create or join an alliance', 'Press G to open Alliance. Create a named team or enter a friend’s six-character join code. An alliance can have up to 12 members. Teams are session-based, so do not treat an invite code as permanent account membership.', { steps: ['Open Alliance with G.', 'Create a team or enter the shared join code.', 'Confirm your member list before fighting together.'] }),
    section('alliance-friendly-fire', 'Friendly-fire settings', 'The leader can turn friendly fire on or off for alliance members. New alliances start with friendly fire off. This setting concerns your own team; it does not make all other players friendly.', { note: 'Agree on the setting before a group encounter. A shelter and an alliance are different systems.', related: ['survival', 'enemies'] }),
  ] },
  { id: 'soldiers', title: 'Soldiers & Missions', icon: 'flag', summary: 'Build a five-person squad, upgrade individuals and manage their availability.', tags: 'npc companion recruit nickname recovery respawn mission 24 hours', sections: [
    section('your-squad', 'Your squad', 'You can own up to five soldiers. Each soldier is a separate individual with a nickname and S1–S5 progression. Recruit through the Gold market, then use its individual deploy, recall and upgrade actions. Upgrade conditions are shown for that soldier.', { note: 'Recruitment and upgrading are different purchases. Read the action’s current Gold and level requirement before confirming.' }),
    section('soldier-support', 'Combat support & recovery', 'Deployed soldiers follow and approach valid nearby enemies, firing when within range. They respect safe areas, obstacles and team targeting rules. They are support units, not a guarantee of winning every fight. A soldier that dies enters a 120-second recovery period; its timer remains after a refresh.', { cards: [['INDIVIDUAL', 'Name and upgrade each soldier separately.'], ['RECOVERY', 'Wait for the saved timer to finish.'], ['AVAILABILITY', 'A recovering soldier or one on a mission cannot be used as normal combat support.']] }),
    section('soldier-missions', '24-hour missions', 'Choose an available soldier in the offgame Market’s Missions tab. Sending an active soldier requires recalling it from combat. Its tier at the start determines the mission reward. After 24 hours, return and claim the Gold; refreshing does not complete a mission early.', { table: { headers: ['Tier', 'Name', 'Gold after 24 hours'], rows: [['S1', 'Recruit', '80'], ['S2', 'Patrol', '160'], ['S3', 'Rifleman', '280'], ['S4', 'Operator', '440'], ['S5', 'Elite', '650']] }, note: 'These are in-game Gold rewards. They are not a promised cash return.', related: ['market', 'faq'] }),
  ] },
  { id: 'market', title: 'Market, VIP & Economy', icon: 'package', summary: 'Know what you are buying, how delivery works and which features are available.', tags: 'eth usd price supply luck box odds gold vip nft token rewards payment', sections: [
    section('two-markets', 'Two ways to obtain supplies', 'The in-game Gold market lets you sell unwanted items and parts and manage soldiers. Tactical Supply on the home and loadout screens offers account packages purchased with ETH on Robinhood Chain. All Gold uses the same balance.'),
    section('package-reference', 'Package reference', 'This table is a summary, not the complete manifest. Packages also contain weapon and equipment crafting parts. Open the Market to see all guaranteed contents before approving payment.', { table: { headers: ['Package', 'USD price', 'Gold', 'Medkit / First Aid / Energy', 'Equipment'], rows: [['Field', '$2', '1,000', '1 / 2 / 1', '—'], ['Supply', '$4', '2,000', '2 / 3 / 2', 'T1 Helmet'], ['Operator', '$6', '3,500', '3 / 4 / 3', 'T1 Helmet + Gloves'], ['Outpost', '$10', '6,000', '4 / 6 / 4', 'T1 Helmet + Vest + Gloves']] } }),
    section('luck-box-odds', 'Equipment Luck Box', 'The $2 box grants 1,000 Gold and five independent material draws. There are 15 possible result types, not 15 draws. Duplicate results add quantities. Each draw uses the following distribution; a rare material or calibration is not guaranteed.', { table: { headers: ['Tier', 'Four material families', 'Material chance', 'Calibration chance', 'Tier total'], rows: LUCK_ODDS } }),
    section('payment-and-delivery', 'Payment & delivery', 'USD prices are converted to a short-lived ETH quote. Review the exact amount, recipient, network and expiry, then approve the separate transfer in your wallet. The server verifies the payment before granting contents. Two chain confirmations are a soft confirmation threshold, not Ethereum L1 finality.', { steps: ['Sign in with the same wallet selected for payment on chain 4663.', 'Choose a product and review the server quote.', 'Approve payment in your wallet only when the details are correct.', 'Use History to verify a pending payment with the existing transaction hash. Do not send a second transfer to retry.', 'Check Deliveries for healing or consumable quantities that exceeded your carry limit. Claim them when there is room.'] }),
    section('vip-membership', 'VIP membership', 'VIP costs $5 for 30 days. Renewal extends your existing expiry. While VIP is active, active PvE Gold rewards receive a 10% bonus. This does not mean a bonus on packages, mission Gold or every Gold source.', { note: 'When NFT sales open, members who hold an NFT will be considered VIP for as long as they hold it. NFT ownership verification is not configured yet.' }),
    section('economy-status', 'Current feature status', 'Play and spending should be based on the available features. Gold does not currently have a configured, claimable LastZ exchange rate.', { table: { headers: ['Feature', 'Current status'], rows: [['ETH packages, Luck Box and 30-day VIP', 'Available'], ['Soldier missions', 'Available'], ['Gold → LastZ exchange / token claims', 'Not configured'], ['NFT ownership verification', 'Not configured'], ['VIP saved loadout presets / recolor', 'Not enabled']] }, related: ['wallet', 'soldiers', 'faq'] }),
  ] },
  { id: 'faq', title: 'Troubleshooting & FAQ', icon: 'help', summary: 'Quick answers when an action does not work as expected.', tags: 'help error pending expired disabled locked bug save', sections: [
    section('faq-entry', 'I cannot enter the game', 'The guide is public, but playing requires an authenticated wallet. Check that your wallet is on Robinhood Chain 4663, your selected address matches the signed-in account, your call sign is complete and the world has finished loading. For a world connection error, check your connection and retry.'),
    section('faq-inventory', 'My weapon or craft action is locked', 'You may be viewing the complete weapon catalog instead of only owned items. A recipe can require specific parts, Gold or a player level. Compare every requirement in the Workshop. Owning a different tier does not automatically satisfy the recipe.'),
    section('faq-soldier', 'My soldier is unavailable', 'Check its individual recovery timer and mission status. Recovery takes two minutes and a mission takes 24 hours. Refreshing does not skip either timer. A completed mission still needs its reward to be claimed.'),
    section('faq-payment', 'My quote expired or payment is pending', 'If you have not sent payment, refresh the expired quote from History and review it again. If you have already sent a transaction, retry verification of that same hash. Keep the order ID and transaction hash when asking for help. A provider outage does not mean you should pay again.'),
    section('faq-delivery', 'Some supplies did not fit', 'Healing and consumable carry limits still apply to packages. Open Deliveries and claim the waiting quantities after using supplies to make room. A full bag can leave the delivery pending.'),
    section('faq-guide', 'Will this guide change?', 'Yes. Early Access mechanics and balance can change. This guide describes the currently implemented systems and labels features that are not configured. It does not promise guaranteed drops, token returns or server capacity.', { related: ['getting-started', 'market'] }),
  ] },
];

export function findChapter(id) { return CHAPTERS.find(ch => ch.id === id) || CHAPTERS[0]; }
export function searchGuide(query) {
  const words = query.toLowerCase().trim().split(/\s+/).filter(Boolean);
  if (!words.length) return [];
  return CHAPTERS.flatMap(ch => ch.sections.map(s => ({ chapter: ch, section: s,
    text: [ch.title, ch.tags, s.title, s.text, s.note, ...(s.steps || []), ...(s.cards || []).flat(), ...(s.table?.headers || []), ...(s.table?.rows || []).flat()].join(' ') })))
    .filter(result => words.every(word => result.text.toLowerCase().includes(word))).slice(0, 20);
}
