import os
import re

ROOT = r"c:\Users\ozan\Documents\ChatGPT\lasthoodz 2\lastzhood-main"

doc_lines = []

doc_lines.append("# DEADZONE — Projedeki Türkçe Metinler ve Çeviri Rehberi (çevirilecekler.md)\n")
doc_lines.append("Bu belge, proje genelinde (Frontend kullanıcı arayüzü, oyun içi veri katalogları, backend API/WebSocket sunucu yanıtları ve test dosyaları) tespit edilen tüm Türkçe ifadelerin, dosya yollarının, satır numaralarının ve önerilen İngilizce karşılıklarının eksiksiz dökümüdür.\n")

doc_lines.append("## Özet Dağılım Tablosu\n")
doc_lines.append("| Kategori | Dosya(lar) | Açıklama |")
doc_lines.append("|---|---|---|")
doc_lines.append("| **1. Frontend UI Bileşenleri** | `MarketPanel.jsx`, `CraftPanel.jsx`, `Inventory.jsx`, `RadialMenu.jsx`, `dialog.jsx`, `EquipmentThumbnail.jsx` | Butonlar, sekmeler, stat etiketleri, uyarılar, dialog kapatma ve erişilebilirlik metinleri. |")
doc_lines.append("| **2. Katalog & Konfigürasyon** | `frontend/src/game/equipmentConfig.js`, `backend/equipment.py` | 18 ekipman parçası, 15 craft hammaddesi, 5 refakatçi asker unvanı/rolü ve detay açıklamaları. |")
doc_lines.append("| **3. Backend Sunucu & WS Yanıtları** | `backend/server.py`, `backend/soldier.py`, `backend/equipment.py`, `backend/loot.py` | HTTP hata mesajları, WebSocket aksiyon başarı/hata bildirimleri, tüccar satış logları. |")
doc_lines.append("| **4. Test Dosyaları & Assertion'lar** | `MarketPanel.test.jsx`, `CraftPanel.test.jsx`, `backend/tests/*.py` | Arayüz test sorguları, WebSocket regresyon assertion'ları ve test docstring'leri. |\n")

# Detailed sections
doc_lines.append("---\n")
doc_lines.append("## 1. Frontend Kullanıcı Arayüzü (UI Components)\n")

# 1.1 MarketPanel.jsx
doc_lines.append("### 1.1 `frontend/src/components/MarketPanel.jsx`\n")
doc_lines.append("| Satır | Mevcut Türkçe İfade | Önerilen İngilizce Karşılık | Tür / Bağlam |")
doc_lines.append("|---|---|---|---|")
doc_lines.append("| L106 | `BAKİYE:` | `BALANCE:` | UI Başlık |")
doc_lines.append("| L107 | `{playerGold} ALTIN` | `{playerGold} GOLD` | Para Birimi |")
doc_lines.append("| L121 | `ASKER YOLDAŞLAR ({active}/5 AKTİF · {owned}/5 SAHİP)` | `MERCENARY SQUAD ({active}/5 ACTIVE · {owned}/5 OWNED)` | Sekme Başlığı |")
doc_lines.append("| L128 | `TÜCCARA SAT (SELL)` | `SELL TO TRADER` | Sekme Başlığı |")
doc_lines.append("| L135 | `ÖZEL PAKETLER` | `SPECIAL BUNDLES` | Sekme Başlığı |")
doc_lines.append("| L164 | `GÖREVDE (AKTİF)` | `DEPLOYED (ACTIVE)` | Asker Durum Rozeti |")
doc_lines.append("| L166 | `KIŞLADA` | `IN BARRACKS (STANDBY)` | Asker Durum Rozeti |")
doc_lines.append("| L168 | `{s.price} ALTIN` | `{s.price} GOLD` | Fiyat Etiketi |")
doc_lines.append("| L173 | `S{s.tier}→S{next.tier} · {next.weapon} · {cost} ALTIN · LVL {req}` | `S{s.tier}→S{next.tier} · {next.weapon} · {cost} GOLD · LVL {req}` | Terfi Özeti |")
doc_lines.append("| L177 | `CAN (HP)` | `HEALTH (HP)` | Stat Başlığı |")
doc_lines.append("| L181 | `SİLAH` | `WEAPON` | Stat Başlığı |")
doc_lines.append("| L185 | `HASAR ÇARPANI` | `DAMAGE MULTIPLIER` | Stat Başlığı |")
doc_lines.append("| L189 | `ATIŞ HIZI / MENZİL` | `FIRE RATE / RANGE` | Stat Başlığı |")
doc_lines.append("| L202 | `LVL {req} GEREKLİ` / `YETERSİZ ALTIN` / `SATIN AL VE BAĞLA` | `LVL {req} REQUIRED` / `INSUFFICIENT GOLD` / `RECRUIT & BIND` | Satın Alma Butonu |")
doc_lines.append("| L211 | `GERİ ÇEK (DEAKTİF ET)` | `RECALL (DEACTIVATE)` | Asker Butonu |")
doc_lines.append("| L220 | `GÖREVE ÇAĞIR (AKTİF ET)` | `DEPLOY (ACTIVATE)` | Asker Butonu |")
doc_lines.append("| L223 | `YÜKSELT` | `UPGRADE` | Asker Terfi Butonu |")
doc_lines.append("| L228 | `BOŞ KADRO YUVASI` | `EMPTY ROSTER SLOT` | Boş Yuva Başlığı |")
doc_lines.append("| L228 | `S1 asker bireysel olarak alınır ve sonra yükseltilir.` | `S1 mercenaries are recruited individually and upgraded.` | Yuva Açıklaması |")
doc_lines.append("| L228 | `ASKER AL — S1 / 500 ALTIN` | `RECRUIT MERCENARY — S1 / 500 GOLD` | Satın Alma Butonu |")
doc_lines.append("| L229 | `KADRO KAPASİTESİ DOLU (5/5)` | `ROSTER CAPACITY FULL (5/5)` | Bilgi Mesajı |")
doc_lines.append("| L243 | `MALZEMELER` | `MATERIALS` | Satış Kategorisi |")
doc_lines.append("| L250 | `SİLAH PARÇALARI` | `WEAPON PARTS` | Satış Kategorisi |")
doc_lines.append("| L264 | `TIBBİ SARF` | `MEDICAL SUPPLIES` | Satış Kategorisi |")
doc_lines.append("| L271 | `SİLAHLAR` | `WEAPONS` | Satış Kategorisi |")
doc_lines.append("| L287 | `Mevcut: {count} adet · Fiyat: {price} Altın/adet` | `In Stock: {count} pcs · Price: {price} Gold/pc` | Fiyat Bilgisi |")
doc_lines.append("| L296 | `1x SAT (+{price}g)` | `SELL 1x (+{price}g)` | Satış Butonu |")
doc_lines.append("| L305 | `5x SAT (+{price*5}g)` | `SELL 5x (+{price*5}g)` | Satış Butonu |")
doc_lines.append("| L319 | `Satılacak silah parçanız yok.` | `No weapon parts available to sell.` | Boş Liste Uyarısı |")
doc_lines.append("| L334 | `Mevcut: {count} adet · Fiyat: {price} Altın/adet` | `In Stock: {count} pcs · Price: {price} Gold/pc` | Fiyat Bilgisi |")
doc_lines.append("| L343 | `1x SAT (+{price}g)` | `SELL 1x (+{price}g)` | Satış Butonu |")
doc_lines.append("| L357 | `Satılacak donanımınız yok.` | `No equipment available to sell.` | Boş Liste Uyarısı |")
doc_lines.append("| L370 | `{stat} · Fiyat: {price} Altın` | `{stat} · Price: {price} Gold` | Fiyat Bilgisi |")
doc_lines.append("| L379 | `SAT (+{price}g)` | `SELL (+{price}g)` | Satış Butonu |")
doc_lines.append("| L394 | `İlk Yardım Kiti (Faid)` | `First Aid Kit (Faid)` | Eşya Adı |")
doc_lines.append("| L395 | `Mevcut: {count} adet · Fiyat: 4 Altın/adet` | `In Stock: {count} pcs · Price: 4 Gold/pc` | Fiyat Bilgisi |")
doc_lines.append("| L404 | `1x SAT (+4g)` | `SELL 1x (+4g)` | Satış Butonu |")
doc_lines.append("| L410 | `Büyük Medkit` | `Large Medkit` | Eşya Adı |")
doc_lines.append("| L411 | `Mevcut: {count} adet · Fiyat: 8 Altın/adet` | `In Stock: {count} pcs · Price: 8 Gold/pc` | Fiyat Bilgisi |")
doc_lines.append("| L420 | `1x SAT (+8g)` | `SELL 1x (+8g)` | Satış Butonu |")
doc_lines.append("| L439 | `Başlangıç silahı satılamaz` / `Fiyat: {price} Altın` | `Starter weapon cannot be sold` / `Price: {price} Gold` | Fiyat / Koruma |")
doc_lines.append("| L448 | `SATILAMAZ` / `SİLAHI SAT (+{price}g)` | `UNSELLABLE` / `SELL WEAPON (+{price}g)` | Satış Butonu |")
doc_lines.append("| L469 | `Robinhood Chain akıllı sözleşme doğrulamalı taktik silah ve paraşüt indirme sandığı.` | `Robinhood Chain smart contract verified tactical weapon and airdrop crate.` | Paket Açıklaması |")
doc_lines.append("| L471 | `• AK-47 Muharebe Tüfeği` | `• AK-47 Assault Rifle` | Paket İçeriği |")
doc_lines.append("| L472 | `• T2 Kompozit Gövde Zırhı` | `• T2 Composite Body Armor` | Paket İçeriği |")
doc_lines.append("| L473 | `• 500 Altın` | `• 500 Gold` | Paket İçeriği |")
doc_lines.append("| L476 | `ZİNCİR ÜZERİNDE MINT ET (YAKINDA)` | `MINT ON CHAIN (COMING SOON)` | Paket Butonu |")
doc_lines.append("| L483 | `ELİTE OPERATOR BUNDLE` | `ELITE OPERATOR BUNDLE` | Paket Başlığı |")
doc_lines.append("| L485 | `Tüm 3. Seviye ekipman parçaları ve S5 Seçkin Muhafız sözleşmesi.` | `All Tier 3 equipment pieces and S5 Elite Mercenary contract.` | Paket Açıklaması |")
doc_lines.append("| L487 | `• S5 Seçkin Asker Sözleşmesi` | `• S5 Elite Mercenary Contract` | Paket İçeriği |")
doc_lines.append("| L488 | `• T3 Kalibrasyon Kartuşu ×3` | `• T3 Calibration Cartridge ×3` | Paket İçeriği |")
doc_lines.append("| L489 | `• 2500 Altın` | `• 2500 Gold` | Paket İçeriği |")
doc_lines.append("| L492 | `ZİNCİR ÜZERİNDE MINT ET (YAKINDA)` | `MINT ON CHAIN (COMING SOON)` | Paket Butonu |\n")

# 1.2 CraftPanel.jsx
doc_lines.append("### 1.2 `frontend/src/components/CraftPanel.jsx`\n")
doc_lines.append("| Satır | Mevcut Türkçe İfade | Önerilen İngilizce Karşılık | Tür / Bağlam |")
doc_lines.append("|---|---|---|---|")
doc_lines.append("| L195 | `Balistik Kumaş → Aramid Lif` | `Ballistic Fabric → Aramid Fiber` | Dönüşüm Tarifi Adı |")
doc_lines.append("| L198 | `Çelik Plaka → Seramik Plaka` | `Steel Plate → Ceramic Plate` | Dönüşüm Tarifi Adı |")
doc_lines.append("| L201 | `Naylon Kayış → Takviyeli Bağlantı` | `Nylon Strap → Reinforced Binding` | Dönüşüm Tarifi Adı |")
doc_lines.append("| L202 | `Takviyeli Bağlantı → Titanyum Bağlantı` | `Reinforced Binding → Titanium Binding` | Dönüşüm Tarifi Adı |")
doc_lines.append("| L207 | `T1 Kalibrasyon → T2 Kalibrasyon` | `T1 Calibration → T2 Calibration` | Dönüşüm Tarifi Adı |")
doc_lines.append("| L208 | `T2 Kalibrasyon → T3 Kalibrasyon` | `T2 Calibration → T3 Calibration` | Dönüşüm Tarifi Adı |")
doc_lines.append("| L505 | `LVL {req} (SİZ: {lvl})` | `LVL {req} (YOU: {lvl})` | Seviye Karşılaştırması |")
doc_lines.append("| L506 | `{gold} ALTIN` | `{gold} GOLD` | Altın Gereksinimi |")
doc_lines.append("| L528 | `ZATEN ÜRETİLDİ` | `ALREADY CRAFTED` | Buton Durumu |")
doc_lines.append("| L528 | `SEVİYE YETERSİZ` | `LEVEL TOO LOW` | Buton Durumu |")
doc_lines.append("| L528 | `YETERSİZ ALTIN` | `INSUFFICIENT GOLD` | Buton Durumu |")
doc_lines.append("| L528 | `EKİPMANI ÜRET (+0)` | `CRAFT EQUIPMENT (+0)` | Üretim Butonu |")
doc_lines.append("| L528 | `MALZEME EKSİK` | `MISSING MATERIALS` | Buton Durumu |")
doc_lines.append("| L542 | `Henüz sahip olduğunuz bir donanım yok. Önce \"CRAFT EQUIPMENT\" sekmesinden donanım üretin.` | `No equipment owned yet. Craft equipment first from the \"CRAFT EQUIPMENT\" tab.` | Boş Liste Bildirimi |")
doc_lines.append("| L605 | `GEREKLİ LVL {req} (SİZ: {lvl})` | `REQUIRED LVL {req} (YOU: {lvl})` | Seviye Karşılaştırması |")
doc_lines.append("| L606 | `{gold} ALTIN` | `{gold} GOLD` | Altın Gereksinimi |")
doc_lines.append("| L619 | `MAKSİMUM GELİŞTİRME (+2) TAMAMLANDI` | `MAXIMUM UPGRADE (+2) ACHIEVED` | Geliştirme Rozeti |")
doc_lines.append("| L631 | `MAKSİMUM SEVİYE` | `MAX LEVEL` | Buton Durumu |")
doc_lines.append("| L631 | `YÜKSELT (+{lvl})` | `UPGRADE (+{lvl})` | Geliştirme Butonu |")
doc_lines.append("| L660 | `{cost} ALTIN` | `{cost} GOLD` | Dönüşüm Bedeli |")
doc_lines.append("| L666 | `GEREKLİ` | `REQUIRED` | Malzeme Gereksinimi |")
doc_lines.append("| L686 | `EN AZ 3 ADET GEREKLİ` | `AT LEAST 3 REQUIRED` | Buton Durumu |")
doc_lines.append("| L686 | `DÖNÜŞTÜR (3→1)` | `CONVERT (3→1)` | Dönüştürme Butonu |\n")

# 1.3 Inventory.jsx
doc_lines.append("### 1.3 `frontend/src/components/Inventory.jsx`\n")
doc_lines.append("| Satır | Mevcut Türkçe İfade | Önerilen İngilizce Karşılık | Tür / Bağlam |")
doc_lines.append("|---|---|---|---|")
doc_lines.append("| L268 | `[ BOŞ YUVA ]` | `[ EMPTY SLOT ]` | Ekipman Yuvası |")
doc_lines.append("| L269 | `Kuşanmak için tıklayın` | `Click to equip` | Yuva İpucu |")
doc_lines.append("| L280 | `{slotName} YUVASI` | `{slotName} SLOT` | Yuva Başlığı |")
doc_lines.append("| L287 | `ÇIKAR` | `UNEQUIP` | Çıkarma Butonu |")
doc_lines.append("| L305 | `SAHİP OLUNAN EKİPMANLAR` | `OWNED EQUIPMENT` | Bölüm Başlığı |")
doc_lines.append("| L307 | `Bu yuvaya uygun ekipmanınız yok. Atölyeden (C) yeni ekipman üretebilirsiniz.` | `No suitable equipment for this slot. Craft new gear in Workshop (C).` | Boş Liste Uyarısı |")
doc_lines.append("| L328 | `KUŞANILDI` / `KUŞAN` | `EQUIPPED` / `EQUIP` | Kuşanma Butonları |")
doc_lines.append("| L345 | `ÜRETİM & KALİBRASYON MALZEMELERİ (15 MATERYAL)` | `CRAFTING & CALIBRATION MATERIALS (15 ITEMS)` | Bölüm Başlığı |")
doc_lines.append("| L366 | `TIBBİ SARF MALZEMELERİ & SİLAH PARÇALARI` | `MEDICAL SUPPLIES & WEAPON PARTS` | Bölüm Başlığı |")
doc_lines.append("| L375 | `TÜKET` | `CONSUME` | Enerji İçeceği Tüketim Butonu |\n")

# 1.4 RadialMenu.jsx, EquipmentThumbnail.jsx, dialog.jsx
doc_lines.append("### 1.4 `RadialMenu.jsx`, `EquipmentThumbnail.jsx` & `dialog.jsx`\n")
doc_lines.append("| Dosya | Satır | Mevcut Türkçe İfade | Önerilen İngilizce Karşılık | Tür / Bağlam |")
doc_lines.append("|---|---|---|---|---|")
doc_lines.append("| `RadialMenu.jsx` | L24 | `hint: 'AŞAĞI / BOTTOM'` | `hint: 'BOTTOM'` | Menü Yön İpucu |")
doc_lines.append("| `RadialMenu.jsx` | L44 | `hint: 'SAĞ / RIGHT'` | `hint: 'RIGHT'` | Menü Yön İpucu |")
doc_lines.append("| `RadialMenu.jsx` | L145 | `BOTTOM · AŞAĞI` | `BOTTOM` | Menü Dilimi |")
doc_lines.append("| `RadialMenu.jsx` | L183 | `RIGHT · SAĞ` | `RIGHT` | Menü Dilimi |")
doc_lines.append("| `RadialMenu.jsx` | L234 | `PAZAR & ASKERLER (M) ↗` | `MARKET & SQUAD (M) ↗` | Hızlı Kısayol |")
doc_lines.append("| `dialog.jsx` | L39 | `aria-label=\"Kapat\"` | `aria-label=\"Close\"` | Erişilebilirlik |")
doc_lines.append("| `dialog.jsx` | L42 | `<span className=\"sr-only\">Kapat</span>` | `<span className=\"sr-only\">Close</span>` | Erişilebilirlik |")
doc_lines.append("| `EquipmentThumbnail.jsx` | L12 | `aria-label={`${item.name} görseli`}` | `aria-label={`${item.name} thumbnail`}` | Erişilebilirlik |\n")

doc_lines.append("---\n")
doc_lines.append("## 2. Oyun Katalogları ve Veri Yapılandırması\n")

# 2.1 equipmentConfig.js
doc_lines.append("### 2.1 `frontend/src/game/equipmentConfig.js`\n")
doc_lines.append("#### Ekipman Yuvaları (Slots)")
doc_lines.append("| ID | Mevcut Türkçe Adı | Önerilen İngilizce Adı |")
doc_lines.append("|---|---|---|")
doc_lines.append("| `hands` | `HANDS / ELDİVEN` | `HANDS` |")
doc_lines.append("| `backpack` | `BACKPACK / ÇANTA` | `BACKPACK` |\n")

doc_lines.append("#### 18 Ekipman Parçası (Items & Descriptions)")
doc_lines.append("| ID | Slot / Tier | Mevcut Ad & Stat | Mevcut Açıklama | Önerilen İngilizce Ad & Açıklama |")
doc_lines.append("|---|---|---|---|---|")
doc_lines.append("| `helm_t1` | head / T1 | `Taktik Kask` (`+3 Zırh`) | `Hafif çelik takviyeli koruyucu başlık.` | `Tactical Helmet` (`+3 Armor`): `Protective headgear with lightweight steel reinforcement.` |")
doc_lines.append("| `helm_t2` | head / T2 | `Kompozit Kask` (`+6 Zırh`) | `Seramik katmanlı gelişmiş koruma başlığı.` | `Composite Helmet` (`+6 Armor`): `Advanced protective helmet with ceramic layering.` |")
doc_lines.append("| `helm_t3` | head / T3 | `Balistik Ağır Kask` (`+9 Zırh`) | `En üst düzey balistik kompozit baş zırhı.` | `Heavy Ballistic Helmet` (`+9 Armor`): `Top-tier ballistic composite head armor.` |")
doc_lines.append("| `vest_t1` | body / T1 | `Hafif Hücum Yeleği` (`+6 Zırh`) | `Temel balistik koruma sağlayan taktik yelek.` | `Light Assault Vest` (`+6 Armor`): `Tactical vest offering baseline ballistic protection.` |")
doc_lines.append("| `vest_t2` | body / T2 | `Taktik Plaka Taşıyıcı` (`+12 Zırh`) | `Seramik plakalarla donatılmış gövde zırhı.` | `Tactical Plate Carrier` (`+12 Armor`): `Body armor equipped with ceramic ballistic plates.` |")
doc_lines.append("| `vest_t3` | body / T3 | `Ağır Taarruz Yeleği` (`+18 Zırh`) | `Ağır muharebe şartları için kompozit gövde zırhı.` | `Heavy Assault Vest` (`+18 Armor`): `Composite body armor built for extreme combat.` |")
doc_lines.append("| `pants_t1` | legs / T1 | `Güçlendirilmiş Pantolon` (`+3 Zırh`) | `Kevlar liflerle örülmüş dayanıklı pantolon.` | `Reinforced Trousers` (`+3 Armor`): `Durable trousers woven with protective Kevlar fibers.` |")
doc_lines.append("| `pants_t2` | legs / T2 | `Muharebe Pantolonu` (`+6 Zırh`) | `Eklem korumalı taktik askeri pantolon.` | `Combat Trousers` (`+6 Armor`): `Tactical combat trousers with reinforced joint pads.` |")
doc_lines.append("| `pants_t3` | legs / T3 | `Zırhlı Taarruz Pantolonu` (`+9 Zırh`) | `Kompozit bacak plakalarıyla donatılmış ağır alt zırh.` | `Armored Assault Pants` (`+9 Armor`): `Heavy lower armor fitted with composite leg plates.` |")
doc_lines.append("| `gloves_t1` | hands / T1 | `Taktik Atış Eldiveni` (`-%2 Doldurma`) | `Kavramayı artıran hafif şarjör doldurma eldiveni.` | `Tactical Shooting Gloves` (`-2% Reload Time`): `Lightweight gloves enhancing weapon grip and reload.` |")
doc_lines.append("| `gloves_t2` | hands / T2 | `Hızlı Çekiş Eldiveni` (`-%4 Doldurma`) | `Silah hakimiyetini ve hızını artıran eldiven.` | `Quick-Draw Gloves` (`-4% Reload Time`): `Combat gloves improving handling and reload speed.` |")
doc_lines.append("| `gloves_t3` | hands / T3 | `Hassas Kompozit Eldiven` (`-%6 Doldurma`) | `Maksimum hızlı şarjör değiştirme desteği.` | `Precision Composite Gloves` (`-6% Reload Time`): `Ergonomic tactical gloves for maximum reload speed.` |")
doc_lines.append("| `boots_t1` | feet / T1 | `Hafif Devriye Botu` (`+%1 Hız`) | `Aşınmaya dayanıklı esnek tabanlı bot.` | `Light Patrol Boots` (`+1% Move Speed`): `Flexible, wear-resistant all-terrain patrol boots.` |")
doc_lines.append("| `boots_t2` | feet / T2 | `Hızlı İntikal Botu` (`+%2 Hız`) | `Hızlı yer değiştirme sağlayan taktik bot.` | `Rapid Response Boots` (`+2% Move Speed`): `Tactical boots engineered for quick repositioning.` |")
doc_lines.append("| `boots_t3` | feet / T3 | `Taktik Taarruz Botu` (`+%3 Hız`) | `Ağır zeminlerde maksimum depar kabiliyeti.` | `Tactical Assault Boots` (`+3% Move Speed`): `Maximum sprint mobility on rough terrain.` |")
doc_lines.append("| `pack_t1` | backpack / T1 | `Kompakt Sırt Çantası` (`+%3 Dayanıklılık`) | `Ağırlık merkezini dengeleyerek stamina yeniler.` | `Compact Backpack` (`+3% Stamina Regen`): `Balances load distribution to boost stamina recovery.` |")
doc_lines.append("| `pack_t2` | backpack / T2 | `Saha Operasyon Çantası` (`+%6 Dayanıklılık`) | `Ergonomik askeri yük dağıtım çantası.` | `Field Ops Pack` (`+6% Stamina Regen`): `Ergonomic military pack designed for sustained operations.` |")
doc_lines.append("| `pack_t3` | backpack / T3 | `Genişletilmiş Sefer Çantası` (`+%9 Dayanıklılık`) | `En yüksek seviye depar ve stamina rejenerasyonu.` | `Expedition Pack` (`+9% Stamina Regen`): `High-capacity tactical pack for peak stamina efficiency.` |\n")

doc_lines.append("#### 15 Craft & Kalibrasyon Malzemesi (Materials)")
doc_lines.append("| ID | Family / Tier | Mevcut Türkçe Adı | Önerilen İngilizce Adı |")
doc_lines.append("|---|---|---|---|")
doc_lines.append("| `fabric_t1` | fabric / T1 | `Balistik Kumaş` | `Ballistic Fabric` |")
doc_lines.append("| `fabric_t2` | fabric / T2 | `Aramid Lif` | `Aramid Fiber` |")
doc_lines.append("| `fabric_t3` | fabric / T3 | `Karbon Fiber Kumaş` | `Carbon Fiber Weave` |")
doc_lines.append("| `plate_t1` | plate / T1 | `Çelik Plaka` | `Steel Plate` |")
doc_lines.append("| `plate_t2` | plate / T2 | `Seramik Plaka` | `Ceramic Plate` |")
doc_lines.append("| `plate_t3` | plate / T3 | `Kompozit Plaka` | `Composite Plate` |")
doc_lines.append("| `binding_t1` | binding / T1 | `Naylon Kayış` | `Nylon Strap` |")
doc_lines.append("| `binding_t2` | binding / T2 | `Takviyeli Bağlantı` | `Reinforced Binding` |")
doc_lines.append("| `binding_t3` | binding / T3 | `Titanyum Bağlantı` | `Titanium Binding` |")
doc_lines.append("| `mechanism_t1` | mechanism / T1 | `Mekanik Yay` | `Mechanical Spring` |")
doc_lines.append("| `mechanism_t2` | mechanism / T2 | `Hassas Dişli` | `Precision Gear` |")
doc_lines.append("| `mechanism_t3` | mechanism / T3 | `Pnömatik Mekanizma` | `Pneumatic Mechanism` |")
doc_lines.append("| `calibration_t1` | calibration / T1 | `T1 Kalibrasyon Kartuşu` | `T1 Calibration Cartridge` |")
doc_lines.append("| `calibration_t2` | calibration / T2 | `T2 Kalibrasyon Kartuşu` | `T2 Calibration Cartridge` |")
doc_lines.append("| `calibration_t3` | calibration / T3 | `T3 Kalibrasyon Kartuşu` | `T3 Calibration Cartridge` |\n")

doc_lines.append("#### Refakatçi Askerler (Mercenary Squad S1–S5)")
doc_lines.append("| Tier | Mevcut Ad | Mevcut Rol & Silah | Mevcut Açıklama | Önerilen İngilizce Karşılık |")
doc_lines.append("|---|---|---|---|---|")
doc_lines.append("| **S1** | `Asker S1 (Çaylak / Recruit)` | `Giriş Seviye Destek` (Glock 18) | `Hafif yan ateş desteği sağlar. Yakın mesafede sahibini korur.` | **Name:** `Soldier S1 (Recruit)`<br>**Role:** `Entry Support`<br>**Desc:** `Provides covering sidearm fire. Protects owner at close quarters.` |")
doc_lines.append("| **S2** | `Asker S2 (Devriye / Patrol)` | `Av Tüfeği Muhafızı` (Pompalı Tüfek) | `Yakın temas muharebesinde yüksek kitle hasarı sağlar.` | **Name:** `Soldier S2 (Patrol)`<br>**Role:** `Shotgun Guardian`<br>**Desc:** `Delivers high point-blank crowd damage in close-range combat.` |")
doc_lines.append("| **S3** | `Asker S3 (Piyade / Rifleman)` | `Orta Menzil Taarruz` (AK-47) | `Orta menzilde sürekli otomatik yaylım ateşiyle baskı kurar.` | **Name:** `Soldier S3 (Rifleman)`<br>**Role:** `Mid-Range Assault`<br>**Desc:** `Suppresses hostile targets at medium range with sustained rifle bursts.` |")
doc_lines.append("| **S4** | `Asker S4 (Operatör / Operator)` | `Hızlı İntikal SMG` (Vector) | `Yüksek atış hızıyla hedefleri hızla eritir.` | **Name:** `Soldier S4 (Operator)`<br>**Role:** `Rapid Mobility SMG`<br>**Desc:** `Eliminates agile targets rapidly with blistering submachine fire rate.` |")
doc_lines.append("| **S5** | `Asker S5 (Seçkin Muhafız / Elite)` | `Ağır Makineli Bastırma` (M4) | `En yüksek can ve menzile sahip üst düzey askeri destek birimi.` | **Name:** `Soldier S5 (Elite Guard)`<br>**Role:** `Heavy Support Fire`<br>**Desc:** `Peak-tier mercenary unit boasting maximum HP, accuracy, and engagement range.` |\n")

# 2.2 backend/equipment.py catalog descriptions
doc_lines.append("### 2.2 `backend/equipment.py` (Katalog Açıklamaları ve İsimleri)\n")
doc_lines.append("Backend tarafında `EQUIPMENT_CATALOG` ve `CRAFT_MATERIALS` sözlüklerinde yer alan ve yukarıdaki 2.1 tablosuyla eşleşen Türkçe metinler:\n")
doc_lines.append("- L17, L21, L25: `helm_t1/t2/t3` `description`: *Mat çelik yuvarlak kabuk...*, *Köşeli balistik kabuk...*, *Kesik yan profilli kompozit kabuk...* -> İngilizce karşılıkları verilmeli.")
doc_lines.append("- L31, L35, L39: `vest_t1/t2/t3` `description`: *İnce kumaş panel...*, *Ön ve arka balistik plaka...*, *Segmentli göğüs plaka...*")
doc_lines.append("- L45, L49, L53: `pants_t1/t2/t3` `description`: *Kumaş uyluk pedleri...*, *Kayışlı sert dizlik...*, *Hareketli segmentli uyluk...*")
doc_lines.append("- L59, L63, L67: `gloves_t1/t2/t3` `description`: *Parmakları açık kumaş...*, *Tam parmak, kauçuk eklem...*, *Kompozit eklem, takviyeli avuç...*")
doc_lines.append("- L73, L77, L81: `boots_t1/t2/t3` `description`: *Deri/kumaş, sade bağcık...*, *Kalın bilek desteği...*, *Hafif katmanlı bilek koruma...*")
doc_lines.append("- L87, L91, L95: `pack_t1/t2/t3` `description`: *Küçük rulo kapaklı...*, *Yan cepli dikdörtgen...*, *Sert sırt paneli...*")
doc_lines.append("- L109-131: Malzeme isimleri: `Balistik Kumaş`, `Çelik Plaka`, `Naylon Kayış`, `Takviyeli Bağlantı`, `Titanyum Bağlantı`, `T1/T2/T3 Kalibrasyon Kartuşu`.\n")

doc_lines.append("---\n")
doc_lines.append("## 3. Backend Sunucu & WebSocket Mesajları (Server & Engine)\n")

# 3.1 backend/server.py
doc_lines.append("### 3.1 `backend/server.py`\n")
doc_lines.append("| Satır | Mevcut Türkçe Hata / Başarı Mesajı | Önerilen İngilizce Karşılık | İşlev |")
doc_lines.append("|---|---|---|---|")
doc_lines.append("| L296 | `'Giriş yapmanız gerekiyor.'` | `'Authentication required.'` | HTTP 401 Hatası |")
doc_lines.append("| L363 | `'Asker geri çekildi.'` | `'Mercenary recalled.'` | REST Başarı Yanıtı |")
doc_lines.append("| L366 | `'Bu askere sahip değilsiniz.'` | `'You do not own this mercenary.'` | HTTP 400 Hatası |")
doc_lines.append("| L371 | `'En fazla beş asker göreve çağrılabilir.'` | `'Maximum 5 mercenaries can be deployed.'` | HTTP 400 Hatası |")
doc_lines.append("| L379 | `f\"{name} göreve çağrıldı!\"` | `f\"{name} deployed!\"` | REST Başarı Yanıtı |")
doc_lines.append("| L507 | `reason='Sunucu dolu.'` | `reason='Server is full.'` | WebSocket 1013 Kapanış |")
doc_lines.append("| L588 | `'Asker kimliği gerekli.'` | `'Mercenary ID is required.'` | WS `action_error` |")
doc_lines.append("| L599 | `'Asker kimliği gerekli.'` | `'Mercenary ID is required.'` | WS `action_error` |\n")

# 3.2 backend/soldier.py
doc_lines.append("### 3.2 `backend/soldier.py`\n")
doc_lines.append("| Satır | Mevcut Türkçe Hata / Başarı Mesajı | Önerilen İngilizce Karşılık | İşlev |")
doc_lines.append("|---|---|---|---|")
doc_lines.append("| L113 | `'En fazla beş askere sahip olabilirsiniz.'` | `'You can own a maximum of 5 mercenaries.'` | Alım Kapasite Sınırı |")
doc_lines.append("| L114 | `'Yetersiz altın. Gerekli: 500 altın.'` | `'Insufficient gold. Required: 500 gold.'` | Alım Altın Hatası |")
doc_lines.append("| L118 | `'S1 asker kadroya katıldı.'` | `'S1 mercenary recruited to roster.'` | Alım Başarı Mesajı |")
doc_lines.append("| L122 | `'Asker bulunamadı.'` | `'Mercenary not found.'` | Terfi Bulunamadı Hatası |")
doc_lines.append("| L124 | `'Asker zaten maksimum seviyede.'` | `'Mercenary is already at maximum tier.'` | Terfi Sınır Hatası |")
doc_lines.append("| L126 | `f\"Gerekli seviye: {lvl}.\"` | `f\"Required level: {lvl}.\"` | Terfi Seviye Hatası |")
doc_lines.append("| L127 | `f\"Yetersiz altın. Gerekli: {cost} altın.\"` | `f\"Insufficient gold. Required: {cost} gold.\"` | Terfi Altın Hatası |")
doc_lines.append("| L129 | `f\"Asker S{tier + 1} seviyesine yükseltildi.\"` | `f\"Mercenary upgraded to Tier S{tier + 1}.\"` | Terfi Başarı Mesajı |")
doc_lines.append("| L133 | `'Asker bulunamadı.'` | `'Mercenary not found.'` | Aktivasyon Hatası |")
doc_lines.append("| L136 | `'En fazla beş asker görevde olabilir.'` | `'Maximum 5 mercenaries can be active.'` | Aktif Kadro Sınırı |")
doc_lines.append("| L139 | `'Asker göreve çağrıldı.'` / `'Asker geri çekildi.'` | `'Mercenary deployed.'` / `'Mercenary recalled.'` | Aktivasyon Başarı Mesajı |\n")

# 3.3 backend/equipment.py (Action responses)
doc_lines.append("### 3.3 `backend/equipment.py` (Üretim, Geliştirme, Kuşanma ve Satış Yanıtları)\n")
doc_lines.append("| Satır | Mevcut Türkçe Mesaj | Önerilen İngilizce Karşılık | İşlev |")
doc_lines.append("|---|---|---|---|")
doc_lines.append("| L338 | `\"Geçersiz ekipman tarifi.\"` | `\"Invalid equipment recipe.\"` | Üretim Hatası |")
doc_lines.append("| L342 | `f\"Seviyeniz yetersiz. Gerekli seviye: {lvl}.\"` | `f\"Level too low. Required level: {lvl}.\"` | Üretim Seviye Hatası |")
doc_lines.append("| L350 | `f\"Yetersiz altın. Gerekli: {gold} altın.\"` | `f\"Insufficient gold. Required: {gold} gold.\"` | Üretim Altın Hatası |")
doc_lines.append("| L359 | `f\"Yetersiz kalibrasyon kartuşu: {part} ({has}/{need}).\"` | `f\"Insufficient calibration cartridges: {part} ({has}/{need}).\"` | Üretim Malzeme Hatası |")
doc_lines.append("| L362 | `f\"Yetersiz malzeme: {part} ({has}/{need}).\"` | `f\"Insufficient materials: {part} ({has}/{need}).\"` | Üretim Malzeme Hatası |")
doc_lines.append("| L381 | `f\"{name} başarıyla üretildi!\"` | `f\"{name} successfully crafted!\"` | Üretim Başarı Mesajı |")
doc_lines.append("| L388 | `\"Bu ekipmana sahip değilsiniz.\"` | `\"You do not own this equipment.\"` | Geliştirme Hatası |")
doc_lines.append("| L398 | `f\"Yükseltme için seviyeniz yetersiz. Gerekli: {lvl}.\"` | `f\"Level too low for upgrade. Required: {lvl}.\"` | Geliştirme Seviye Hatası |")
doc_lines.append("| L402 | `f\"Yetersiz altın. Gerekli: {gold} altın.\"` | `f\"Insufficient gold. Required: {gold} gold.\"` | Geliştirme Altın Hatası |")
doc_lines.append("| L410 | `f\"Yetersiz kalibrasyon kartuşu: {part} ({has}/{need}).\"` | `f\"Insufficient calibration cartridges: {part} ({has}/{need}).\"` | Geliştirme Malzeme Hatası |")
doc_lines.append("| L413 | `f\"Yetersiz malzeme: {part} ({has}/{need}).\"` | `f\"Insufficient materials: {part} ({has}/{need}).\"` | Geliştirme Malzeme Hatası |")
doc_lines.append("| L424 | `f\"{name} seviye +{lvl} yapıldı!\"` | `f\"{name} upgraded to level +{lvl}!\"` | Geliştirme Başarı Mesajı |")
doc_lines.append("| L430 | `\"Geçersiz ekipman yuvası.\"` | `\"Invalid equipment slot.\"` | Kuşanma Hatası |")
doc_lines.append("| L436 | `f\"{slot} yuvasındaki ekipman çıkarıldı.\"` | `f\"Equipment in {slot} slot unequipped.\"` | Çıkarma Başarı Mesajı |")
doc_lines.append("| L439 | `\"Bu ekipmana sahip değilsiniz.\"` | `\"You do not own this equipment.\"` | Kuşanma Hatası |")
doc_lines.append("| L443 | `\"Ekipman bu yuvaya takılamaz.\"` | `\"Equipment cannot be equipped to this slot.\"` | Yuva Uyuşmazlığı |")
doc_lines.append("| L446 | `f\"{name} kuşandı.\"` | `f\"{name} equipped.\"` | Kuşanma Başarı Mesajı |")
doc_lines.append("| L455 | `\"Farklı türdeki malzemeler birbirine dönüştürülemez.\"` | `\"Different material types cannot be converted.\"` | Dönüşüm Hatası |")
doc_lines.append("| L461 | `\"Sadece bir üst kademe kalibrasyon kartuşuna dönüştürülebilir.\"` | `\"Can only be converted to the next tier calibration cartridge.\"` | Dönüşüm Kademe Hatası |")
doc_lines.append("| L466 | `f\"Dönüşüm için en az 3 adet {src} gereklidir.\"` | `f\"At least 3 {src} required for conversion.\"` | Dönüşüm Miktar Hatası |")
doc_lines.append("| L468 | `f\"Yetersiz altın. Gerekli: {gold} altın.\"` | `f\"Insufficient gold. Required: {gold} gold.\"` | Dönüşüm Altın Hatası |")
doc_lines.append("| L473 | `f\"3 adet {src} başarıyla 1 adet {tgt} kartuşuna dönüştürüldü.\"` | `f\"Successfully converted 3x {src} into 1x {tgt} cartridge.\"` | Dönüşüm Başarılı |")
doc_lines.append("| L479 | `\"Geçersiz malzeme.\"` | `\"Invalid material.\"` | Dönüşüm Hatası |")
doc_lines.append("| L482 | `\"Yalnızca aynı malzeme ailesi içinde dönüşüm yapılabilir.\"` | `\"Conversion only allowed within the same material family.\"` | Aile Uyuşmazlığı |")
doc_lines.append("| L485 | `\"Sadece bir üst kademe malzemeye dönüştürülebilir.\"` | `\"Can only convert to the next tier material.\"` | Kademe Uyuşmazlığı |")
doc_lines.append("| L490 | `f\"Dönüşüm için en az 3 adet {name} gereklidir.\"` | `f\"At least 3 {name} required for conversion.\"` | Miktar Hatası |")
doc_lines.append("| L492 | `f\"Yetersiz altın. Gerekli: {gold} altın.\"` | `f\"Insufficient gold. Required: {gold} gold.\"` | Altın Hatası |")
doc_lines.append("| L497 | `f\"3 adet {src} başarıyla 1 adet {tgt} malzemesine dönüştürüldü.\"` | `f\"Successfully converted 3x {src} into 1x {tgt}.\"` | Dönüşüm Başarılı |")
doc_lines.append("| L503 | `\"Geçersiz satış miktarı.\"` | `\"Invalid sale quantity.\"` | Satış Miktar Hatası |")
doc_lines.append("| L512 | `\"Yetersiz kalibrasyon kartuşu.\"` | `\"Insufficient calibration cartridges.\"` | Satış Hata |")
doc_lines.append("| L517 | `\"Yetersiz malzeme.\"` | `\"Insufficient materials.\"` | Satış Hata |")
doc_lines.append("| L521 | `f\"{amt}x malzeme satıldı. +{gold} altın kazanıldı.\"` | `f\"Sold {amt}x material(s). +{gold} gold earned.\"` | Satış Başarı |")
doc_lines.append("| L529 | `\"Yetersiz silah parçası.\"` | `\"Insufficient weapon parts.\"` | Satış Hata |")
doc_lines.append("| L542 | `f\"{amt}x silah parçası satıldı. +{gold} altın kazanıldı.\"` | `f\"Sold {amt}x weapon part(s). +{gold} gold earned.\"` | Satış Başarı |")
doc_lines.append("| L548 | `\"Bu ekipmana sahip değilsiniz.\"` | `\"You do not own this equipment.\"` | Satış Hata |")
doc_lines.append("| L551 | `\"Geçersiz ekipman.\"` | `\"Invalid equipment.\"` | Satış Hata |")
doc_lines.append("| L568 | `f\"{name} satıldı. +{gold} altın kazanıldı.\"` | `f\"Sold {name}. +{gold} gold earned.\"` | Satış Başarı |")
doc_lines.append("| L572 | `\"Geçersiz sarf malzemesi.\"` | `\"Invalid consumable item.\"` | Satış Hata |")
doc_lines.append("| L576 | `\"Yetersiz tıbbi malzeme.\"` | `\"Insufficient medical supplies.\"` | Satış Hata |")
doc_lines.append("| L580 | `f\"{amt}x sarf malzemesi satıldı. +{gold} altın kazanıldı.\"` | `f\"Sold {amt}x medical supply. +{gold} gold earned.\"` | Satış Başarı |")
doc_lines.append("| L584 | `\"Başlangıç silahı (Glock 18) satılamaz.\"` | `\"Starter weapon (Glock 18) cannot be sold.\"` | Satış Güvenlik Koruması |")
doc_lines.append("| L586 | `\"Geçersiz veya satılamayan silah.\"` | `\"Invalid or unsellable weapon.\"` | Satış Hata |")
doc_lines.append("| L589 | `\"Bu silaha sahip değilsiniz.\"` | `\"You do not own this weapon.\"` | Satış Hata |")
doc_lines.append("| L601 | `f\"{item_key.upper()} silahı satıldı. +{gold} altın kazanıldı.\"` | `f\"Sold {item_key.upper()} weapon. +{gold} gold earned.\"` | Satış Başarı |")
doc_lines.append("| L603 | `\"Geçersiz kategori.\"` | `\"Invalid sale category.\"` | Satış Hata |\n")

# 3.4 backend/loot.py
doc_lines.append("### 3.4 `backend/loot.py`\n")
doc_lines.append("| Satır | Mevcut Türkçe Hata / Başarı Mesajı | Önerilen İngilizce Karşılık | İşlev |")
doc_lines.append("|---|---|---|---|")
doc_lines.append("| L50 | `'Bu sarf malzemesi şu anda kullanılamaz.'` | `'This consumable cannot be used right now.'` | Tüketim Hatası |")
doc_lines.append("| L53 | `'Enerji içeceği zaten kullanıldı.'` | `'Energy drink already consumed.'` | Tekrarlı İstek (Idempotency) |")
doc_lines.append("| L56 | `'Enerji içeceği stoğunuz yok.'` | `'No energy drinks in stock.'` | Stok Hatası |")
doc_lines.append("| L67 | `'ENERGY DRINK: 60 SN ×2 DAYANIKLILIK YENİLENMESİ.'` | `'ENERGY DRINK: 60 SEC ×2 STAMINA REGENERATION.'` | Tüketim Başarı Bildirimi |\n")

doc_lines.append("---\n")
doc_lines.append("## 4. Test Dosyaları & Assertion'lar\n")
doc_lines.append("Geliştirici test dosyalarında ve birim test assertion'larında yer alan Türkçe ifadeler (kodlar İngilizceye çevrildiğinde bu testlerdeki stringler de güncellenmelidir):\n")

doc_lines.append("### 4.1 Frontend Testleri\n")
doc_lines.append("| Dosya | Satır | Türkçe Assertion / Metin | Not |")
doc_lines.append("|---|---|---|---|")
doc_lines.append("| `CraftPanel.test.jsx` | L60, L65 | `aria-label=\"Taktik Kask görseli\"` | Thumbnail aria-label kontrolü |")
doc_lines.append("| `MarketPanel.test.jsx` | L42 | `expect(...).toContain('KADRO KAPASİTESİ DOLU (5/5)')` | Kadro doluluk metni kontrolü |")
doc_lines.append("| `MarketPanel.test.jsx` | L43 | `button.textContent.includes('ASKER AL')` | Satın al butonu sorgusu |")
doc_lines.append("| `MarketPanel.test.jsx` | L49, L62, L65 | `button.textContent.includes('YÜKSELT')` | Terfi butonu sorgusu |")
doc_lines.append("| `MarketPanel.test.jsx` | L56 | `button.textContent.includes('GERİ ÇEK')` | Geri çek butonu sorgusu |\n")

doc_lines.append("### 4.2 Backend Testleri\n")
doc_lines.append("| Dosya | Satır | Türkçe Metin / Yorum | Not |")
doc_lines.append("|---|---|---|---|")
doc_lines.append("| `test_soldier_ws_account_regression.py` | L103 | `assert ... == 'S1 asker kadroya katıldı.'` | WS yanıt doğrulaması |")
doc_lines.append("| `test_soldier_ws_account_regression.py` | L111 | `assert 'En fazla beş' in ...` | WS kapasite hata kontrolü |")
doc_lines.append("| `test_backend_short_smoke.py` | L1 | `\"\"\"Kısa odaklı DEADZONE backend smoke + birim testleri...\"\"\"` | Modül docstring'i |")
doc_lines.append("| `test_live_ws_focus.py` | L1, L212 | `\"\"\"Module: public API + gerçek websocket akışında...\"\"\"`, `WS sample (6 oyuncu/5s)` | Modül ve log açıklaması |")
doc_lines.append("| `test_network_channel_focus.py` | L1 | `\"\"\"Module: network.ClientChannel + engine tick isolation...\"\"\"` | Modül docstring'i |")
doc_lines.append("| `test_skin_ws_contract.py` | L1, L73-171 | `\"\"\"Skin seçim ve websocket senkronizasyon sözleşmesi...\"\"\"` + 8 adet test adım yorumu | Test docstring ve açıklamaları |")
doc_lines.append("| `test_iteration6_game_unit_focus.py` | L1-35 | Test senaryo açıklamaları ve docstring'ler | Test docstring'leri |\n")

doc_lines.append("---\n")
doc_lines.append("## 5. Çeviri Uygulama Planı ve Güvenlik Adımları\n")
doc_lines.append("1. **Frontend UI Çevirisi:** `MarketPanel.jsx`, `CraftPanel.jsx`, `Inventory.jsx` ve `RadialMenu.jsx` dosyalarındaki Türkçe metinler yukarıdaki tabloda önerilen İngilizce karşılıklarla güncellenmelidir.")
doc_lines.append("2. **Katalog Senkronizasyonu:** `equipmentConfig.js` ve `backend/equipment.py` dosyaları eş zamanlı çevrilmelidir; frontend ve backend tarafında eşya ve malzeme isimlerinin birebir eşleşmesi bozulmamalıdır.")
doc_lines.append("3. **Sunucu Yanıtları & Test Güncellemeleri:** `backend/server.py`, `backend/soldier.py`, `backend/equipment.py` ve `backend/loot.py` hata/başarı mesajları İngilizceye çevrildiğinde, `test_soldier_ws_account_regression.py`, `MarketPanel.test.jsx` ve `CraftPanel.test.jsx` içerisindeki string kontrolleri de eş zamanlı güncellenmelidir.")
doc_lines.append("4. **Regresyon Kontrolü:** Değişiklik sonrası `pytest` ve `npm run build` çalıştırılarak hiçbir testin veya build adımının kırılmadığı doğrulanmalıdır.\n")

output_content = "\n".join(doc_lines)

target_path = os.path.join(ROOT, "çevirilecekler.md")
with open(target_path, "w", encoding="utf-8") as f:
    f.write(output_content)

print(f"Successfully generated {target_path} with {len(output_content)} characters.")
